version: '3'

services:

  proxy:
    image: alexpierry/desafio2_proxy
    container_name: proxy
    networks:
      - node-network
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    image: alexpierry/desafio2_app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - "database:/data/db"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - "3306:3306"

networks:
  node-network:
    driver: bridge

volumes:
  database:
